"""add_target_questions_to_interview

Revision ID: 04dc892d84ee
Revises: 27f706f2ddbd
Create Date: 2026-04-10 16:03:59.696546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dc892d84ee'
down_revision: Union[str, None] = '27f706f2ddbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('interviews', sa.Column('target_questions', sa.Integer(), nullable=True, server_default='5'))
    op.execute("UPDATE interviews SET target_questions = 5 WHERE target_questions IS NULL")
    op.alter_column('interviews', 'target_questions', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'target_questions')
    # ### end Alembic commands ###
