"""add job_applications

Revision ID: 089b233a971c
Revises: 4d2be616b449
Create Date: 2026-04-17 19:36:11.704202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089b233a971c'
down_revision: Union[str, None] = '4d2be616b449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'reviewed', 'shortlisted', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_role_id'), 'job_applications', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_job_applications_student_id'), 'job_applications', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_student_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_role_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
