"""add experience and portfolio fields to student

Revision ID: 4d2be616b449
Revises: 34439c1c7337
Create Date: 2026-04-17 19:28:05.217806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2be616b449'
down_revision: Union[str, None] = '34439c1c7337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('student_profiles', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('student_profiles', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_roles', sa.JSON(), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_locations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'preferred_locations')
    op.drop_column('student_profiles', 'preferred_roles')
    op.drop_column('student_profiles', 'portfolio_url')
    op.drop_column('student_profiles', 'github_url')
    op.drop_column('student_profiles', 'linkedin_url')
    op.drop_column('student_profiles', 'years_of_experience')
    op.drop_column('student_profiles', 'experience_level')
    # ### end Alembic commands ###
