"""add approval and feedback to scheduled_interviews

Revision ID: 53a0aa0a004f
Revises: a66989daa520
Create Date: 2026-04-17 08:52:19.560620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a0aa0a004f'
down_revision: Union[str, None] = 'a66989daa520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    approval_enum = sa.Enum('pending', 'approved', 'declined', 'not_required', name='approvalstatus')
    approval_enum.create(op.get_bind(), checkfirst=True)
    outcome_enum = sa.Enum('hire', 'next_round', 'reject', name='interviewoutcome')
    outcome_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('scheduled_interviews', sa.Column('college_approval', approval_enum, nullable=False, server_default='pending'))
    op.add_column('scheduled_interviews', sa.Column('college_decline_reason', sa.Text(), nullable=True))
    op.add_column('scheduled_interviews', sa.Column('feedback_rating', sa.Integer(), nullable=True))
    op.add_column('scheduled_interviews', sa.Column('feedback_notes', sa.Text(), nullable=True))
    op.add_column('scheduled_interviews', sa.Column('feedback_outcome', outcome_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_interviews', 'feedback_outcome')
    op.drop_column('scheduled_interviews', 'feedback_notes')
    op.drop_column('scheduled_interviews', 'feedback_rating')
    op.drop_column('scheduled_interviews', 'college_decline_reason')
    op.drop_column('scheduled_interviews', 'college_approval')
    # ### end Alembic commands ###
