"""add difficulty_level to interview_attempts

Revision ID: 9ac983cf019d
Revises: 05a77248be9f
Create Date: 2026-04-17 11:05:02.958410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac983cf019d'
down_revision: Union[str, None] = '05a77248be9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_attempts', sa.Column('difficulty_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_attempts', 'difficulty_level')
    # ### end Alembic commands ###
