"""create scheduled_interviews table

Revision ID: a66989daa520
Revises: d50b88aedcdd
Create Date: 2026-04-16 23:19:56.355146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66989daa520'
down_revision: Union[str, None] = 'd50b88aedcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=True),
    sa.Column('candidate_type', sa.Enum('platform', 'external', name='candidatetype'), nullable=False),
    sa.Column('talent_profile_id', sa.Integer(), nullable=True),
    sa.Column('candidate_name', sa.String(length=200), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=True),
    sa.Column('candidate_phone', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('interviewer_name', sa.String(length=200), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'rescheduled', 'completed', 'cancelled', name='schedulestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reschedule_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['talent_profile_id'], ['talent_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_interviews_company_id'), 'scheduled_interviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_scheduled_interviews_id'), 'scheduled_interviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_interviews_id'), table_name='scheduled_interviews')
    op.drop_index(op.f('ix_scheduled_interviews_company_id'), table_name='scheduled_interviews')
    op.drop_table('scheduled_interviews')
    # ### end Alembic commands ###
