"""add college_name to users

Revision ID: a816264a32bd
Revises: c6f002a49864
Create Date: 2026-04-16 22:13:28.237121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a816264a32bd'
down_revision: Union[str, None] = 'c6f002a49864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'college_name')
    # ### end Alembic commands ###
