"""enrich interview data fields

Revision ID: c6f002a49864
Revises: 04dc892d84ee
Create Date: 2026-04-16 11:22:23.714461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f002a49864'
down_revision: Union[str, None] = '04dc892d84ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_answers', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('interview_answers', sa.Column('response_time_seconds', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('target_role', sa.String(length=200), nullable=True))
    op.add_column('interviews', sa.Column('target_industry', sa.String(length=200), nullable=True))
    op.add_column('interviews', sa.Column('overall_summary', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('overall_feedback', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('questions_answered', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'questions_answered')
    op.drop_column('interviews', 'overall_feedback')
    op.drop_column('interviews', 'overall_summary')
    op.drop_column('interviews', 'target_industry')
    op.drop_column('interviews', 'target_role')
    op.drop_column('interviews', 'duration_seconds')
    op.drop_column('interview_answers', 'response_time_seconds')
    op.drop_column('interview_answers', 'word_count')
    # ### end Alembic commands ###
